web:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/web/**'

app:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/web/source/app/**'
          - 'apps/web/index.html'

styles:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/web/source/**/*.css'

assets:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/web/source/assets/**'
          - 'apps/web/public/**'

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - 'mise.toml'
          - '**/tsconfig*.json'
          - '**/vite.config.*'
          - '**/.oxlintrc.json'
          - '**/.prettierrc*'
          - '**/.prettierignore'
          - '**/.editorconfig'
          - '.gitignore'
          - 'stylelint.config.*'
          - '.vscode/**'

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/package.json'
          - 'bun.lock'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'documentation/**'
          - 'LICENSE'
