name: Performance Request
description: Request a performance improvement
labels:
  - performance

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should be improved?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed?
    validations:
      required: true
